### ISSUE TITLE
update columns name with multiple VueyeTables.

### ISSUE THREAD

**Issue by sailfish009** [boussadjra/vueye-table#12]
i want to use multiple data table, so i need to change columns name.
to change columns name, i have tried v-show and v-if.
if i am using v-show, then columns name changes, but some columns from searched result  now showing.
and if using v-if, all columns field from searched result fine, but columns name not changed.

```
<VueyeTable v-show="x == y" :columns="columns_1" :data="rows_1" :title="result1">
<VueyeTable v-show="u == v" :columns="columns_2" :data="rows_2" :title="result2">

<VueyeTable v-if="x == y" :columns="columns_1" :data="rows_1" :title="result1">
<VueyeTable v-if="u == v" :columns="columns_2" :data="rows_2" :title="result2">
```

**Comment by boussadjra** [comment]
Could you show some screenshots of that issues because I don't understand the problem

**Comment by sailfish009** [comment]
I'll upload screenshots if I can upload them when absolutely necessary.

This is a configuration with only one data table per page. However, depending on the search method, the type and number of searched data are different, so the column name and number of the data table must be changed dynamically.

**Comment by boussadjra** [comment]
Sorry, I can't catch your issue, please create an example in codesanbox that explains this

**Comment by boussadjra** [comment]
I found the issue source and I'm working on to fix, when I release a new version I will let you know

**Comment by boussadjra** [comment]
Now you could uninstall the current version using the following command :

       npm uninstall --save vueye-table 

then reinstall the new one  : 

      npm install vueye-table --save

if you've any new issue don't hesitate to post it

**Comment by sailfish009** [comment]
`yarn upgrade   // works for me.`

`v-show` works, but ` v-if` doesn't. okay for me (using v-show now).

**Comment by boussadjra** [comment]
why do you need to use v-if/v-show?

**Comment by sailfish009** [comment]
because, want to see only one data table with multiple search option.

**Comment by boussadjra** [comment]
add `:header-display="false"` and use your own search option

**Comment by sailfish009** [comment]
no need to add something, current solution works fine for me.
