### ISSUE TITLE
Changing Heading columns styles

### ISSUE THREAD

**Issue by pooria121** [boussadjra/vueye-table#15]
I would like to change the heading names styles (e.g., font, color,etc) - I override the default style names with no luck. I would appreciate any hint.

**Comment by boussadjra** [comment]
please share what you have tried so far

**Comment by pooria121** [comment]
in my component scss file I have added:

 .ve-table-head-cell{
color:white !important;
}

hoping that it would overwrite existing color.

**Comment by boussadjra** [comment]
could you share the script and the table code?

**Comment by pooria121** [comment]
I can't share the entire vue component - but I have the table as:
<VueyeTable
   key="historical" 
    :data="historical_holdings"
    :columns="historical_holdings_columns"
    title="Historical Holdings"
  ></VueyeTable>

at at the bottom of my Vue component I have added 
<style src="./Portfolio.scss" lang="scss" scoped /> where inside Portfolio.scss I have added:
.ve-table-head-cell{
color:white !important;
}

Note that all custom styles that I have added to portfolio.scss are successfully applied except ve-table-head-cell.
Is there something specific that you are looking for that I might be able to share (except entire Vue Component code) ? Also, is it even correct to create another "ve-table-head-cell" ?

**Comment by boussadjra** [comment]
It should work as in this example https://codesandbox.io/s/vueye-table-forked-l6kjn?file=/src/App.vue

try out :

```
<style src="./Portfolio.scss" lang="scss" scoped /> where inside Portfolio.scss I have added:
</style>
<style scoped>
.ve-table-head-cell{
color:white !important;
}
</style>

``

**Comment by pooria121** [comment]
The problem was on my side. My SCSS is "scoped" which would apply the css to the current component and not to VueyeTable which is considered a separate component. Thanks again.
