### ISSUE TITLE
Not find the library in NPM

### ISSUE THREAD

**Issue by Luismij** [boussadjra/vueye-table#2]
Hey, I'm using this library in one of my projects,  but when I run npm install, I get an error.
When I check the package here: https://www.npmjs.com/package/vueye-datatable/v/0.1.13
I get an error.
I need to know how to solve this. 
Thanks

**Comment by ckmirafss** [comment]
Same here @Luismij , waiting for an update for this library. Have you tried vue-datatables?

**Comment by ckmirafss** [comment]
@Luismij try this https://vuejsexamples.com/a-data-table-created-using-vue-js/

**Comment by boussadjra** [comment]
Hi @Luismij i have updated the component using the new composition API, try the following command `npm i vueye-table` instead of `npm i vueye-datatable`
